### ISSUE TITLE
Complation fails due to FirmwareReceiver

### ISSUE THREAD

**Issue by klasrocket** [collin80/GVRET#17]
Not able to complie and not really sure why, can't find any file including a struct for FirmwareReceiver though.

Get the following output from Arduino IDE 1.6.5, tried 1.6.9 with same result.

```
Arduino: 1.6.5 (Linux), Board: "Arduino Due (Programming Port)"

GVRET:56: error: 'FirmwareReceiver' does not name a type
GVRET.ino: In function 'void setup()':
GVRET:293: error: 'fwReceiver' was not declared in this scope
GVRET:293: error: expected type-specifier before 'FirmwareReceiver'
GVRET:293: error: expected ';' before 'FirmwareReceiver'
'FirmwareReceiver' does not name a type

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

```

**Comment by collin80** [comment]
FirmwareReceiver is an Arduino library. The source code for it can be found in my repos: https://github.com/collin80/FirmwareReceiver

However, I did recently change the layout of FirmwareReceiver to no longer be object oriented. I should have updated GVRET at the same time but it appears I haven't. So, that's an oversight on my part. I do have an updated GVRET that does work with the newest FirmwareReceiver. I think that source is on my work machine though so I'll have to update GVRET on github first thing tomorrow. Sorry for this trouble.

**Comment by collin80** [comment]
No more firmwarereceiver. Be gone!
