### ISSUE TITLE
No saving to EEPROM?

### ISSUE THREAD

**Issue by yoh-there** [collin80/GVRET#2]
Every time I boot up GVRET it tells me it is using the defaults. I could see nothing wrong in the code, but it is what it does. Could be my hardware is fault. Are changes (i.e. bus speed set through SavvyCan) supposed to be saved to EEPROM?

I can test the hardware and check if valid data is in the EEPROM if this is not reproducable.

**Comment by collin80** [comment]
You should not be seeing this behavior. It does save the settings to EEPROM. For instance, you should be able to set the speeds for CAN0 and CAN1 and they'll be that setting from then on when you connect to SavvyCAN or just power it by itself (and use an SDCard). So, something is wrong with your hardware.

**Comment by yoh-there** [comment]
Fair enough. I will check this and report back.

**Comment by yoh-there** [comment]
I think I got it, but would appreciate your confirmation.

Yes, indeed it is a hardware issue. Running this on a Taijiuino and that does not have the little AVR to handle the second USB port. I think your Wire_EEPROM library uses lil'one's EEPROM, as the SAM doesn't have one, am I right?

If I am right, I suggest to close this issue, but can I also humbly suggest to add a few lines in the readme for GVRET that it will not run on a Taijiuino or any Due clone without an additional AVR.

Maybe also add a note to Wire_EEPROM on where it saves it stuff and again that it won't work for boards without an AVR.

Yes I know we cannot document or design for every hardware alternative. I got the Taijiuino as it has the Ethernet pins, which meant more to me than two USB's.

**Comment by collin80** [comment]
No, it uses an I2C connected EEPROM. There are many EEPROMs that all work pretty much the same. The one in use on the CANDue is M24M02-DR

**Comment by yoh-there** [comment]
Ah. That makes sense. And I think the culprit is clear then:

Taijiuino: http://www.elechouse.com/elechouse/index.php?main_page=popup_image&pID=2255

The real Due: https://www.arduino.cc/en/uploads/Main/ArduinoDue_Front.jpg 

The little bugger just below the "www" print. Nowhere to be found on the Taijiuino. Grmpf. Case closed, thank you for your help.

**Comment by yoh-there** [comment]
Just for reference adding this comment: It has nothing to do with the Due versus Taijiuino either. The EEPROM is, other than the AVR boards, a function of the CAN kit as sold through evtv. And you clearly state that in the readme.

And since I tinkered my own CAN hardware, guess what, never thought about the EEPROM. So not only is it indeed a hardware issue, it is entirely in my court.
