### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by devguyplus** [collin80/GVRET#20]
Hi, when I try to compile this project I get this error:

No such file or directory
 #include <MCP2515_sw_can.h>

I'm using Due as board on the IDE.

**Comment by collin80** [comment]
https://github.com/macchina/Single-Wire-CAN-mcp2515

**Comment by per1234** [comment]
@collin80 I'm pretty sure that's the wrong link and you actually meant https://github.com/macchina/mcp2515

**Comment by per1234** [comment]
Ah, I see now. It was changed since that comment: https://github.com/collin80/GVRET/commit/a523287b46f3a6a59c0dbf395eed23304998bb77
