### ISSUE TITLE
Bug in time sync

### ISSUE THREAD

**Issue by yoh-there** [collin80/GVRET#3]
Going through the source code to document the interface, I think there is a bug in the TIME_SYNC block (line 619, build 322). I know it doesn't do a thing now, but it also doesn't reset the state to IDLE. Doesn't that lock it up?

**Comment by collin80** [comment]
You're correct. That feature was never implemented and calling it would have locked up the sketch. Good catch! This oversight has been corrected as of firmware version 323.
